version: '3'

services:

  node:
    build: node
    ports:
      - '3000:3000'
  nginx:
    container_name: pensive_mccarthy
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    depends_on:
      - node