version: '3'

services:

  nginx:
    container_name: nginx_modsec
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    networks:
      - default
  node:
    build: node
    ports:
      - '3000:3000'
    networks:
      - default
    depends_on:
      - nginx
    
networks:
  default: