version: '3'

services:

  web:
    container_name: nginx_modsec
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    networks:
      - default
  app:
    build: app
    
networks:
  default: